import MOCK_DATA from "./MOCK_DATA.json";

let initState = {
  devices: {
    url: "devices",
    title: "Devices",
    currentPage: 0,
    path: ["devices"],
    keyName: "IMEINumber",
    data: {
      deviceId: "",
      IMEINumber: "",
      speedLimit: 0,
      ownerId: "",
      vehcileId: "",
      activationDate: 0,
      enable: true,
      dateCreated: 0,
      dateUpdated: 0,
    },
    apiCallData: MOCK_DATA,
    apiData: MOCK_DATA,
    table: [
      { id: "IMEINumber", name: "INMEI Number", sort: false },
      { id: "owner", name: "Owner Name", sort: false },
      { id: "vehcileId", name: "Vehcile Number", sort: false },
      { id: "dateCreated", name: "Creation Date", sort: false },
    ],
    form: [
      {
        name: "IMEINumber",
        type: "text",
        label: "IMEI Number",
        placeHolder: "1298-AHCG-9551-10JH",
        value: "",
        isRequired: true,
      },
      {
        name: "speedLimit",
        type: "number",
        label: "Speed Limit",
        placeHolder: "20",
        value: 0,
      },
      {
        name: "owner",
        type: "select",
        label: "Select Owner",
        placeHolder: "",
        options: [
          { value: "", label: "Select Owner" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
      },
      {
        name: "vehcileId",
        type: "select",
        label: "Select Vehcile",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
      },
      {
        name: "enable",
        type: "select",
        label: "Status",
        placeHolder: "",
        options: [
          { value: true, label: "Active" },
          { value: false, label: "Inactive" },
        ],
        value: "",
        isRequired: true,
        isAdminOnly: true,
      },
      {
        name: "activationDate",
        type: "date",
        label: "Activation Date",
        placeHolder: "20",
        value: "",
        isRequired: true,
      },
    ],
  },

  owners: {
    url: "owners",
    title: "Owners",
    currentPage: 0,
    path: ["owners"],
    keyName: "ownerId",
    data: {
      ownerId: "",
      firstName: "",
      lastName: "",
      orgName: "",
      regNo: "",
      phoneNumber: "",
      address: "",
      estbDate: "",
      enable: true,
      dateCreated: 0,
      dateUpdated: 0,
      avatar: "",
    },
    apiCallData: [],
    apiData: [],
    table: [
      { id: "firstName", name: "First Name", sort: false },
      { id: "lastName", name: "Last Name", sort: false },
      { id: "orgName", name: "Organisation Name", sort: false },
      { id: "enable", name: "Status", sort: false },
      { id: "dateCreated", name: "Created on", sort: false },
    ],
    form: [
      {
        name: "firstName",
        type: "text",
        label: "First Name",
        placeHolder: "Jhon",
        value: "",
        isRequired: true,
      },
      {
        name: "lastName",
        type: "text",
        label: "Last Name",
        placeHolder: "Doe",
        value: "",
        isRequired: true,
      },
      {
        name: "ownerName",
        type: "text",
        label: "Owner Name",
        placeHolder: "ABC Transport Company",
        value: "",
        isRequired: true,
      },
      {
        name: "regNo",
        type: "text",
        label: "Registartion Number",
        placeHolder: "ABC Transport Company",
        value: "",
      },
      {
        name: "address",
        type: "text",
        label: "Address",
        placeHolder: "Street no 10,Ontario,Canada",
        value: "",
      },
      {
        name: "estbDate",
        type: "date",
        label: "Date of Establishment",
        placeHolder: "",
        value: "",
      },
      {
        name: "enable",
        type: "select",
        label: "Status",
        placeHolder: "",
        options: [
          { value: true, label: "Active" },
          { value: false, label: "Inactive" },
        ],
        value: "",
        isRequired: true,
        isAdminOnly: true,
      },
    ],
  },

  vehicles: {
    url: "vehicles",
    title: "Vehicles",
    currentPage: 0,
    path: ["vehicles"],
    keyName: "vehcileId",
    data: {
      vehcileId: "",
      ownerId: "",
      regNo: "",
      vehcileType: "",
      chasisNo: "",
      builtType: "",
      purchaseDate: "",
      manufactureDate: "",
      tyres: 0,
      details: "",
      drivers: [],
      deviceId: "",
      enable: true,
      dateCreated: 0,
      dateUpdated: 0,
      avatar: "",
    },
    apiCallData: [],
    apiData: [],
    table: [
      { id: "regNo", name: "Registration number", sort: false },
      { id: "vehcileType", name: "Vehicle Type", sort: false },
      { id: "builtType", name: "Built type", sort: false },
      { id: "tyres", name: "Tyres", sort: false },
      { id: "enable", name: "Status", sort: false },
      { id: "dateCreated", name: "Created on", sort: false },
    ],
    form: [
      {
        name: "regNo",
        type: "text",
        label: "Registartion Number",
        placeHolder: "CA 12 1098",
        value: "",
        isRequired: true,
      },
      {
        name: "vehcileType",
        type: "select",
        label: "Vehcile Type",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isRequired: true,
      },
      {
        name: "chasisNo",
        type: "text",
        label: "Chasis Number",
        placeHolder: "AsxpJH678754FD",
        value: "",
        isRequired: true,
      },
      {
        name: "builtType",
        type: "text",
        label: "Built Type",
        placeHolder: "Mercedes 12 Tyre",
        value: "",
      },
      {
        name: "purchaseDate",
        type: "date",
        label: "Date of Purchase",
        placeHolder: "",
        value: "",
      },
      {
        name: "manufactureDate",
        type: "date",
        label: "Date of Manufacture",
        placeHolder: "",
        value: "",
      },
      {
        name: "tyres",
        type: "number",
        label: "Total Tyres",
        placeHolder: "4",
        value: 0,
      },
      {
        name: "details",
        type: "text",
        label: "Details",
        placeHolder: "120 Ton capacity,12 tyres,multi-axle",
        value: "",
        isMulti: true,
      },
      {
        name: "drivers",
        type: "select",
        label: "Assign Drivers",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isMulti: true,
      },
      {
        name: "deviceId",
        type: "select",
        label: "Assign Device",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isAdminOnly: true,
      },
      {
        name: "enable",
        type: "select",
        label: "Status",
        placeHolder: "",
        options: [
          { value: true, label: "Active" },
          { value: false, label: "Inactive" },
        ],
        value: "",
        isRequired: true,
        isAdminOnly: true,
      },
    ],
  },

  drivers: {
    url: "drivers",
    title: "Drivers",
    currentPage: 0,
    path: ["drivers"],
    keyName: "driverId",
    data: {
      driverId: "",
      ownerId: "",
      firstName: "",
      lastName: "",
      dob: "",
      sex: 0,
      dlNumber: "",
      joiningDate: "",
      phoneNumber: "",
      address: "",
      vehciles: [],
      enable: true,
      dateCreated: 0,
      dateUpdated: 0,
      avatar: "",
    },
    apiCallData: [],
    apiData: [],
    table: [
      { id: "firstName", name: "First Name", sort: false },
      { id: "lastName", name: "Last Name", sort: false },
      { id: "dlNumber", name: "License Number", sort: false },
      { id: "tyres", name: "Tyres", sort: false },
      { id: "enable", name: "Status", sort: false },
      { id: "dateCreated", name: "Created on", sort: false },
    ],
    form: [
      {
        name: "firstName",
        type: "text",
        label: "First Name",
        placeHolder: "Jhon",
        value: "",
        isRequired: true,
      },
      {
        name: "lastName",
        type: "text",
        label: "Last Name",
        placeHolder: "Doe",
        value: "",
        isRequired: true,
      },
      {
        name: "sex",
        type: "select",
        label: "Sex",
        placeHolder: "",
        options: [
          { value: 0, label: "Male" },
          { value: 1, label: "Female" },
          { value: 2, label: "Other" },
        ],
        value: 0,
        isRequired: true,
      },
      {
        name: "dob",
        type: "date",
        label: "Date of Birth",
        placeHolder: "",
        value: "",
      },
      {
        name: "joiningDate",
        type: "date",
        label: "Date of Joining",
        placeHolder: "",
        value: "",
      },
      {
        name: "dlNumber",
        type: "text",
        label: "Driving License",
        placeHolder: "AsxpJH678754FD",
        value: "",
        isRequired: true,
      },
      {
        name: "address",
        type: "text",
        label: "Address",
        placeHolder: "12th Street,downtown,California,U.S.A",
        value: "",
      },
      {
        name: "vehciles",
        type: "select",
        label: "Assign Vehciles",
        placeHolder: "",
        options: [
          { value: "", label: "Select Vehcile" },
          { value: "chocolate", label: "Chocolate" },
          { value: "strawberry", label: "Strawberry" },
          { value: "vanilla", label: "Vanilla" },
        ],
        value: "",
        isMulti: true,
      },
      {
        name: "enable",
        type: "select",
        label: "Status",
        placeHolder: "",
        options: [
          { value: true, label: "Active" },
          { value: false, label: "Inactive" },
        ],
        value: "",
        isRequired: true,
        isAdminOnly: true,
      },
    ],
  },

  tickets: {
    url: "tickets",
    title: "Tickets",
    currentPage: 0,
    path: ["tickets"],
    keyName: "ticketId",
    data: {
      ticketId: "",
      ownerId: "",
      subject: "",
      details: "",
      // messages: [{ date: "", message: "", isAdmin: false }],
      messages: [],
      status: false,
      dateCreated: 0,
      dateUpdated: 0,
    },
    apiCallData: MOCK_DATA,
    apiData: MOCK_DATA,
    table: [
      { id: "date", name: "dateCreated", sort: false },
      { id: "subject", name: "Subject", sort: false },
      { id: "ownerId", name: "Owner Name", sort: false },
      { id: "ticketId", name: "Ticket ID", sort: false },
      { id: "enable", name: "Status", sort: false },
      { id: "dateUpdated", name: "Updated on", sort: false },
    ],
    form: [
      {
        name: "followUp",
        type: "text",
        label: "Message",
        placeHolder: "We are lloking into the matter.....",
        value: "",
        isRequired: true,
      },
    ],
    mobileTable: {
      left: {
        avatar: null,
        title: "date",
        sub: "date",
      },
      content: {
        title: ["subject"],
        subTitles: [],
      },
      rightId: "status",
    },
  },

  packages: {
    url: "packages",
    title: "Packages",
    currentPage: 0,
    keyName: "packageId",
    data: {
      packageId: "",
      ownerId: "",
      packageName: "",
      packagePrice: 0.0,
      packageTenure: 0,
      enable: true,
      activationDate: 0,
      dateCreated: 0,
      dateUpdated: 0,
    },
    apiCallData: [],
    apiData: [],
    table: [
      { id: "packageName", name: "Name", sort: false },
      { id: "packagePrice", name: "Price", sort: false },
      { id: "packageTenure", name: "Tenure(Days)", sort: false },
      { id: "enable", name: "Status", sort: false },
      { id: "dateCreated", name: "Created on", sort: false },
    ],
    form: [
      {
        name: "packageName",
        type: "text",
        label: "Name",
        placeHolder: "Monthly Package",
        value: "",
        isRequired: true,
      },
      {
        name: "packagePrice",
        type: "number",
        label: "Price (USD)",
        placeHolder: "10",
        value: 0,
        isRequired: true,
      },
      {
        name: "packageTenure",
        type: "number",
        label: "Tenure (Days)",
        placeHolder: "60",
        value: 0,
        isRequired: true,
      },
      {
        name: "enable",
        type: "checkbox",
        label: "Active",
        placeHolder: "0",
        value: true,
      },
      {
        name: "activationDate",
        type: "date",
        label: "Activation Date",
        placeHolder: "",
        value: "",
      },
    ],
  },
};

export { initState };
